# Base information
baseURL = "https://examplesite.com"
languageCode = "en-gb"
title = "ChongPortfolio"
theme = "hugo-developer-portfolio"
googleAnalytics = ""

# Remove this when using normally
#themesDir = "../" 
#theme = "."
 
#[module]
  #[[module.imports]]
    #path = "github.com/ChongKangRui/hugo-developer-portfolio"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"


# navigation
[menu]

  [[menu.main]]
  name = "About"
  URL = "about"
  weight=1

  [[menu.main]]
  name = "Portfolio"
  URL = "portfolio"
  weight=2

 


[params]
home = "Home"
# Meta data
description = "The website of Chong Kang Rui"
author = "Chong Kang Rui"


  [params.contact]
  enable = true
  formAction = "" #contact form works with formspree.io

  [params.footer]
  email = "chongkangrui@gmail.com"
  address = "Malaysia"
  
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "rainbow_dash"
    tabWidth = 4

